version: '3.8'

# Development override for docker-compose.yml
# This file extends the base configuration with development-friendly settings

services:
  # MongoDB - Development configuration
  mongo:
    environment:
      # Keep the same as base but expose debug info
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: studycontrol
    # Enable MongoDB logging for development
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log", "--logappend"]
    volumes:
      # Use named volume for persistence during development
      - mongo-dev-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Backend API Server - Development configuration
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
      # Use development target if available in Dockerfile
      target: development
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://studycontrol:studycontrol123@mongo:27017/studycontrol
      JWT_SECRET: dev-jwt-secret-key-not-for-production
      JWT_REFRESH_SECRET: dev-refresh-secret-not-for-production
      CORS_ORIGIN: http://localhost:3000
      # Enable debug logging
      DEBUG: app:*
    volumes:
      # Mount source code for hot reload
      - ./server/src:/app/src:ro
      - ./server/package.json:/app/package.json:ro
      - ./server/tsconfig.json:/app/tsconfig.json:ro
      # Mount uploads directory for development
      - ./server/uploads:/app/uploads
    # Use nodemon for hot reload
    command: ["npm", "run", "dev"]
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js Application - Development configuration
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      # Use development target if available in Dockerfile
      target: development
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000/api/v1
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      # Enable Next.js development features
      NEXT_PUBLIC_DEV_MODE: "true"
    volumes:
      # Mount source code for hot reload
      - ./client/app:/app/app:ro
      - ./client/components:/app/components:ro
      - ./client/lib:/app/lib:ro
      - ./client/hooks:/app/hooks:ro
      - ./client/types:/app/types:ro
      - ./client/public:/app/public:ro
      - ./client/package.json:/app/package.json:ro
      - ./client/next.config.ts:/app/next.config.ts:ro
      - ./client/tsconfig.json:/app/tsconfig.json:ro
      - ./client/tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./client/postcss.config.mjs:/app/postcss.config.mjs:ro
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    # Use development server
    command: ["npm", "run", "dev"]
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Development volumes
volumes:
  mongo-dev-data:
    name: studycontrol-mongo-dev-data

# Override network configuration for development
networks:
  studycontrol-network:
    driver: bridge
    name: studycontrol-dev-network